#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - curl

runcmd:
  # Install Node.js & npm (LTS version)
  - curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  - sudo apt-get install -y nodejs

  # Clone the repository
  - git clone https://github.com/Cloud-Explorer/CIDR_Live_blot_stackblitz.git /home/ubuntu/vite-project
  - cd /home/ubuntu/vite-project

  # Install dependencies
  - npm install

  # Build the project
  - npm run build

  # Set up a systemd service to keep Vite running
  - echo "[Unit]
    Description=Vite React App
    After=network.target

    [Service]
    Type=simple
    User=ubuntu
    WorkingDirectory=/home/ubuntu/vite-project
    ExecStart=/usr/bin/npm run dev -- --host
    Restart=always

    [Install]
    WantedBy=multi-user.target" | sudo tee /etc/systemd/system/vite-app.service

  # Reload systemd and start the service
  - sudo systemctl daemon-reload
  - sudo systemctl enable vite-app.service
  - sudo systemctl start vite-app.service

  # Open firewall for Vite on port 5173
  - sudo ufw allow 5173/tcp
  - sudo ufw reload
